manifest-version = 1

[component]
name = "Amazon EventBridge"
version = "0.1.0"

wit-version = "1.0.0"
category = "data-collection"
subcategory = "warehouse"
icon-path = "eventbridge-icon.png"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud)
and [Amazon EventBridge](https://aws.amazon.com/eventbridge/),
allowing you to send events for attribution for a given user.
'''
documentation = "https://github.com/Rbatistab/amazon-event-bridge-component"
repository = "https://github.com/Rbatistab/amazon-event-bridge-component"

[component.build]
command = "cargo build --target wasm32-wasip2 --release && cp ./target/wasm32-wasip2/release/event_bridge_component.wasm event_bridge.wasm"
output_path = "event_bridge.wasm"

# General settings
[component.settings.aws_region]
title = "Your AWS region"
type = "string"
required = true

[component.settings.domain]
title = "Your AWS domain for EventBridge (optional)"
type = "string"

# Access settings
[component.settings.aws_access_key]
title = "Your AWS access key"
type = "string"
required = true

[component.settings.aws_secret_key]
title = "Your AWS Secret Access Key"
type = "string"
required = true

[component.settings.aws_security_token]
title = "Your AWS Security Token (optional)"
type = "string"