manifest-version = 1

[component]
name = "amazon-event-bridge-component"
version = "0.1.0"

category = "data-collection"
subcategory = "attribution"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud) and [Amazon EventBridge](https://aws.amazon.com/eventbridge/),
allowing you to send events for attribution for a given user.
'''
documentation = "https://github.com/Rbatistab/amazon-event-bridge-component"
repository = "https://github.com/Rbatistab/amazon-event-bridge-component"
wit-world-version = "0.4.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release && cp ./target/wasm32-wasip2/release/event_bridge_component.wasm event_bridge.wasm"
output_path = "event_bridge.wasm"

# General settings
[component.settings.aws_region]
title = "Your AWS region"
type = "string"

[component.settings.aws_event_bus]
title = "Your AWS event bus"
type = "string"

# Access settings
# - https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-encryption-key-policy.html
# - https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-infrastructure.html
[component.settings.aws_access_key]
title = "Your AWS access key (optional)"
type = "string"

[component.settings.aws_security_token]
title = "Your AWS Security Token (optional)"
type = "string"

[component.settings.aws_iam_role]
title = "Your AWS IAM Role (optional)"
type = "string"

[componet.settings.aws_acess_policy]
title = "Your AWS Access Policy (optional)"
type = "string"

[component.settings.aws_vpc_endpoint]
title = "Your AWS VPC endpoint (optional)"
type = "string"